server:
  port: 9003

spring:
  application:
    name: his-provider-doctorhome
  cloud:
    alibaba:
      seata:
        enable: true
        tx-service-group: his-order
    nacos:
      discovery:
        server-addr: 192.168.40.129:1111
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/his_lau?characterEncoding=utf8&useSSL=false&useInformationSchema=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #Redis相关配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345

feign:
  hystrix:
    enabled: false
  sentinel:
      enable: true
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
#  feign.client.config.default.connect-timeout=300000 和 feign.client.config.default.read-timeout=300000
logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: mapper/*.xml



